export const MOTIVATIONAL_QUOTES = [
  "Discipline is choosing between what you want now and what you want most.",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
  "The only bad workout is the one that didn't happen.",
  "Motivation gets you going, but discipline keeps you growing.",
  "Suffering is the true test of life.",
  "If it doesn't challenge you, it doesn't change you.",
  "The pain of discipline is nothing like the pain of disappointment.",
  "Your mind will give up a thousand times before your body will.",
  "Do today what others won't so you can live tomorrow what others can't.",
  "The body achieves what the mind believes.",
  "Success isn't always about greatness. It's about consistency.",
  "You don't have to be extreme, just consistent.",
  "Energy flows where attention goes.",
  "Hard work beats talent when talent doesn't work hard.",
  "Look in the mirror. That's your competition.",
  "Action is the foundational key to all success.",
  "Great things never came from comfort zones.",
  "Don't count the days, make the days count.",
  "Suffer the pain of discipline or suffer the pain of regret.",
  "You are one workout away from a good mood.",
  "Excuses don't burn calories.",
  "The difference between who you are and who you want to be is what you do.",
  "What hurts today makes you stronger tomorrow.",
  "Tired is just a state of mind.",
  "You don't find time to exercise. You make time.",
  "Be greater than your excuses.",
  "You miss 100% of the shots you don't take.",
  "Sweat is just fat crying.",
  "Definition of a really good workout: when you hate doing it, but you love finishing it.",
  "Rome wasn't built in a day, but they were laying bricks every hour.",
  "Stop rewarding yourself with food. You are not a dog.",
  "Your health is an investment, not an expense.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Well begun is half done.",
  "Believe you can and you're halfway there.",
  "If you kick a person in the pants responsible for most of your trouble, you wouldn't sit for a month.",
  "Small daily improvements over time lead to stunning results.",
  "It's going to be a journey. It's not a sprint.",
  "Do something today that your future self will thank you for.",
  "The clock is ticking. Are you becoming the person you want to be?",
  "Obstacles are those frightful things you see when you take your eyes off your goal.",
  "There are no shortcuts to any place worth going.",
  "The secret of getting ahead is getting started.",
  "Champions keep playing until they get it right.",
  "The harder the struggle, the more glorious the triumph.",
  "Continuous improvement is better than delayed perfection.",
  "Your current state is not your permanent destination.",
  "Focus on the process, not the outcome.",
  "You don't get what you wish for; you get what you work for.",
  "Push yourself, because no one else is going to do it for you.",
  "Greatness is a state of mind.",
  "Don't limit your challenges. Challenge your limits.",
  "Be stubborn about your goals, but flexible about your methods.",
  "If you want something you've never had, you must be willing to do something you've never done.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Strength does not come from physical capacity. It comes from an indomitable will.",
  "It always seems impossible until it's done.",
  "Fall seven times, stand up eight.",
  "The standard you walk past is the standard you accept.",
  "You cannot look back; you must look forward.",
  "Make each day your masterpiece.",
  "Do not let what you cannot do interfere with what you can do.",
  "Be the change that you wish to see in the world.",
  "The best way to predict the future is to create it.",
  "Act as if what you do makes a difference. It does.",
  "Never give up on a dream just because of the time it will take to accomplish it.",
  "You just can't beat the person who won't give up.",
  "It's not whether you get knocked down; it's whether you get up.",
  "The future depends on what you do today.",
  "Go dynamic, go hard, or go home.",
  "Everything you've ever wanted is on the other side of fear.",
  "Don't wish it were easier. Wish you were better.",
  "You must expect great things of yourself before you can do them.",
  "Opportunities don't happen. You create them.",
  "Too many of us are not living our dreams because we are living our fears.",
  "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.",
  "Let it Happen. ",
  "The man who moves a mountain begins by carrying away small stones.",
  "When you feel like quitting, think about why you started.",
  "The only way to do great work is to love what you do.",
  "A year from now you may wish you had started today.",
  "Be disciplined on the days you don't feel motivated.",
  "A level of thinking that got you here will not get you there.",
  "If you're going through hell, keep going.",
  "Quality is not an act, it is a habit.",
  "Mastering others is strength. Mastering yourself is true power.",
  "Keep your eyes on the stars, and your feet on the ground.",
  "You cannot scale your potential if you stay in your comfort zone.",
  "Better to run than to fade away.",
  "Dream big and dare to fail.",
  "It is during our darkest moments that we must focus to see the light.",
  "Nothing is impossible, the word itself says 'I'm possible'!",
  "The power of imagination makes us infinite.",
  "Believe in yourself and all that you are.",
  "Light tomorrow with today.",
  "You map out your own destiny.",
  "The secret to building a powerhouse habit is immediate execution.",
  "Great works are performed not by strength but by perseverance.",
  "Do the hard work, especially when you don't feel like it.",
  "Conquering others takes force, but conquering yourself makes you invincible.",
  "The path to success is to take massive, determined action."
];